get:
  x-app: birthday
  tags: [ birthday ]
  summary: 获取生日提醒设置列表
  security:
  - wechat: []
  parameters:
    - name: birth_id
      in: query
      type: integer
      required: true
      description: 生日 Id
  responses:
    200:
      description: 设置列表
      schema:
        type: array
        items:
          $ref: "#/definitions/BirthdaySetting"
    default:
      description: 错误
      schema:
        $ref: "#/definitions/ErrorResponse"
post:
  x-app: birthday
  tags: [ birthday ]
  summary: 新增生日提醒设置
  security:
  - wechat: []
  parameters:
    - name: birth_id
      in: formData
      type: integer
      required: true
      description: 生日 Id
    - name: advance
      in: formData
      type: integer
      minimum: 0
      required: true
      description: 当前/提前提醒的天数
    - name: time
      in: formData
      type: string
      required: true
      description: 提醒的时间
  responses:
    201:
      description: 生日
      schema:
        $ref: "#/definitions/BirthdaySetting"
    default:
      description: 错误
      schema:
        $ref: "#/definitions/ErrorResponse"
put:
  x-app: birthday
  tags: [ birthday ]
  summary: 修改生日提醒设置
  security:
  - wechat: []
  parameters:
    - name: setting_id
      in: formData
      type: integer
      required: true
      description: 提醒 Id
    - name: advance
      in: formData
      type: integer
      minimum: 0
      description: 当前/提前提醒的天数
    - name: time
      in: formData
      type: string
      description: 提醒的时间
  responses:
    200:
      description: 生日
      schema:
        $ref: "#/definitions/BirthdaySetting"
    default:
      description: 错误
      schema:
        $ref: "#/definitions/ErrorResponse"
delete:
  x-app: birthday
  tags: [ birthday ]
  summary: 删除生日提醒设置
  security:
  - wechat: []
  parameters:
    - name: setting_id
      in: query
      type: integer
      required: true
      description: 设置 Id
  responses:
    200:
      description: 删除完成
      schema:
        $ref: "#/definitions/SuccessResponse"
    default:
      description: 错误
      schema:
        $ref: "#/definitions/ErrorResponse"
